included:
  - App
  - AppTests
  - AppUITests
  - Tools

whitelist_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_init
  - file_header
  - file_length
  - first_where
  - for_where
  - force_try
  - function_body_length
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nesting
  - no_fallthrough_only
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - reduce_boolean
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - static_operator
  - superfluous_disable_command
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_private_declaration
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - void_return
  - weak_computed_property
  - weak_delegate
  - yoda_condition

attributes:
  always_on_same_line:
    - '@IBAction'
    - '@IBOutlet'
    - '@IBDesignable'
    - '@IBInspectable'
    - '@GKInspectable'
    - '@NSCopying'
    - '@NSManaged'
    - '@dynamic'
    - '@inlinable'
    - '@nonobjc'
    - '@objc'
    - '@objcMembers'
  always_on_line_above:
    - '@dynamicMemberLookup'
    - '@UIApplicationMain'
    - '@NSApplicationMain'
    - '@available'
    - '@convention'
    - '@discardableResult'
    - '@usableFromInline'
    - '@warn_unqualified_access'
    - '@testable'

closure_body_length:
  warning: 20
  error: 40

collection_alignment:
  align_colons: false

colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

conditional_returns_on_newline:
  if_only: false

cyclomatic_complexity:
  warning: 16
  error: 32
  ignores_case_statements: true

deployment_target:
  iOS_deployment_target: '10.0'

discouraged_direct_init:
  types:
    - 'Bundle'
    - 'UIDevice'
    - 'AVAudioSession'

discouraged_object_literal:
  image_literal: true
  color_literal: true

dynamic_inline:
  severity: warning

empty_count:
  severity: warning

file_header:
  required_pattern: |
                    \/\/
                    \/\/  SWIFTLINT_CURRENT_FILENAME
                    \/\/  XcodeGenDemo
                    \/\/

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

force_try:
  severity: warning

function_body_length:
  warning: 40
  error: 80

generic_type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 20
    error: 40
  validates_start_with_lowercase: true
  excluded:
    - 'T'
    - 'U'
    - 'V'

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 80
  validates_start_with_lowercase: true

large_tuple:
  warning: 3
  error: 8

line_length:
  warning: 120
  error: 240
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: true
  ignores_interpolated_strings: false

modifier_order:
  preferred_modifier_order:
    - 'acl'
    - 'setterACL'
    - 'override'
    - 'owned'
    - 'mutators'
    - 'final'
    - 'typeMethods'
    - 'required'
    - 'convenience'
    - 'lazy'
    - 'dynamic'

multiline_arguments:
  first_argument_location: 'same_line'
  only_enforce_after_first_closure_on_first_line: false

nesting:
  type_level:
    warning: 1
    error: 2
  statement_level:
    warning: 4
    error: 8

number_separator:
  minimum_length: 5
  minimum_fraction_length: 5
  exclude_ranges: []

overridden_super_call:
  included:
    - '*'
  excluded: []

private_outlet:
  allow_private_set: false

private_over_fileprivate:
  validate_extensions: true

prohibited_super_call:
  included:
    - '*'
  excluded: []

shorthand_operator:
  severity: warning

statement_position:
  statement_mode: 'default'

switch_case_alignment:
  indented_cases: false

trailing_closure:
  only_single_muted_parameter: true

trailing_comma:
  mandatory_comma: false

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: false

type_body_length:
  warning: 400
  error: 800

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 100
  validates_start_with_lowercase: true

unused_optional_binding:
  ignore_optional_try: false

vertical_whitespace:
  max_empty_lines: 1

warning_threshold: 100
